export const REQUESTED_COUNTRIES = "REQUESTED_COUNTRIES";
export const REQUESTED_COUNTRIES_SUCCEEDED = "REQUESTED_COUNTRIES_SUCCEEDED";
export const REQUESTED_COUNTRIES_FAILED = "REQUESTED_COUNTRIES_FAILED";

export const SET_CURRENT_COUNTRY = "SET_CURRENT_COUNTRY";

export const SET_CURRENT_INDICATOR = "SET_CURRENT_INDICATOR";

