export const REQUESTED_COVID_ALL = "REQUESTED_COVID_ALL";
export const REQUESTED_COVID_ALL_SUCCEEDED = "REQUESTED_COVID_ALL_SUCCEEDED";
export const REQUESTED_COVID_ALL_FAILED = "REQUESTED_COVID_ALL_FAILED";

export const REQUESTED_HISTORICAL_ALL = "REQUESTED_HISTORICAL_ALL";
export const REQUESTED_HISTORICAL_ALL_SUCCEEDED =
  "REQUESTED_HISTORICAL_ALL_SUCCEEDED";
export const REQUESTED_HISTORICAL_ALL_FAILED =
  "REQUESTED_HISTORICAL_ALL_FAILED";
